# Generated by Django 5.2.13 on 2026-04-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='photo_url',
            field=models.URLField(blank=True, default='', max_length=512),
        ),
    ]
