# Generated by Django 5.2.13 on 2026-05-10 15:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tap', '0002_player_photo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('trigger_type', models.CharField(choices=[('total_taps', 'Всего тапов'), ('total_coins_earned', 'Всего заработано монет'), ('prestige_count', 'Количество закалок'), ('items_bought', 'Количество купленных предметов'), ('crystals_spent', 'Потрачено алмазов')], default='total_taps', max_length=50)),
                ('trigger_value', models.PositiveBigIntegerField(default=1000)),
                ('reward_crystals', models.PositiveIntegerField(default=10)),
                ('reward_coins', models.PositiveBigIntegerField(default=0)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['trigger_type', 'trigger_value'],
            },
        ),
        migrations.CreateModel(
            name='CelestialUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('upgrade_type', models.CharField(choices=[('global_income', 'Глобальный множитель дохода'), ('tap_bonus', 'Бонус к тапам'), ('offline_boost', 'Увеличение оффлайн лимита'), ('auto_tap', 'Авто-тап (каждую секунду)')], default='global_income', max_length=50)),
                ('value', models.FloatField(default=1.0)),
                ('price_crystals', models.PositiveIntegerField(default=100)),
                ('max_level', models.PositiveIntegerField(default=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DailyRewardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(unique=True)),
                ('reward_coins', models.PositiveBigIntegerField(default=1000)),
                ('reward_crystals', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('base_income_per_second', models.PositiveBigIntegerField(default=0)),
                ('base_price', models.PositiveBigIntegerField(default=100)),
                ('price_increase_factor', models.FloatField(default=1.15)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='cached_income_per_second',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='crystals',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='last_seen_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='player',
            name='last_sync_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='player',
            name='max_offline_minutes',
            field=models.PositiveIntegerField(default=180),
        ),
        migrations.AddField(
            model_name='player',
            name='prestige_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_earned_all_time',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PlayerDailyReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_claim_date', models.DateField(blank=True, null=True)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('max_streak', models.PositiveIntegerField(default=0)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reward', to='tap.player')),
            ],
        ),
        migrations.CreateModel(
            name='Upgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_celestial', models.BooleanField(default=False)),
                ('upgrade_type', models.CharField(choices=[('click_multiplier', 'Умножитель клика'), ('income_multiplier', 'Умножитель пассивного дохода'), ('offline_extension', 'Увеличение оффлайн лимита'), ('special', 'Особое')], default='income_multiplier', max_length=50)),
                ('value', models.FloatField(default=1.0)),
                ('base_price', models.PositiveBigIntegerField(default=1000)),
                ('min_total_taps', models.PositiveBigIntegerField(default=0)),
                ('min_prestige_count', models.PositiveIntegerField(default=0)),
                ('required_item_quantity', models.PositiveIntegerField(default=0)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('required_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='required_upgrades', to='tap.item')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlayerAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tap.achievement')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='tap.player')),
            ],
            options={
                'unique_together': {('player', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='PlayerCelestialUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celestial_upgrades', to='tap.player')),
                ('upgrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tap.celestialupgrade')),
            ],
            options={
                'unique_together': {('player', 'upgrade')},
            },
        ),
        migrations.CreateModel(
            name='PlayerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tap.item')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tap.player')),
            ],
            options={
                'unique_together': {('player', 'item')},
            },
        ),
        migrations.CreateModel(
            name='PlayerUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrades', to='tap.player')),
                ('upgrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tap.upgrade')),
            ],
            options={
                'unique_together': {('player', 'upgrade')},
            },
        ),
    ]
