# Generated by Django 5.2.13 on 2026-05-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tap', '0005_add_memory_and_resonance_upgrades'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='icon_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='celestialupgrade',
            name='icon_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='icon_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='upgrade',
            name='icon_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='celestialupgrade',
            name='upgrade_type',
            field=models.CharField(choices=[('global_income', 'Глобальный множитель дохода'), ('tap_bonus', 'Бонус к тапам'), ('offline_boost', 'Увеличение оффлайн лимита'), ('auto_tap', 'Авто-тап (каждую секунду)'), ('start_boost', 'Начальный бонус осколков')], default='global_income', max_length=50),
        ),
    ]
