# Generated by Django 5.2.14 on 2026-05-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tap', '0016_add_quantum_resonance_upgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='item',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='show_in_shop',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='upgrade_by',
            field=models.CharField(choices=[('income', 'По доходу в секунду'), ('manual', 'Ручная прокачка в магазине')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='playeritem',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
